spring:
  application:
    name: mesbackend

  datasource:
    url: jdbc:mysql://localhost:3306/mesdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 100MB

file:
  imgFileLocation: C:/mes_tripleJ/mes_back/image