spring:
  application:
    name: mesbackend

  datasource:
    url: jdbc:mysql://localhost:3306/mesdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update